// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tablero_MVC.Context;

#nullable disable

namespace Tablero_MVC.Migrations
{
    [DbContext(typeof(TableroDBContext))]
    [Migration("20231103000630_Segunda")]
    partial class Segunda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tablero_MVC.Models.Tablero", b =>
                {
                    b.Property<int>("IDTablero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTablero"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.HasKey("IDTablero");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Tableros");
                });

            modelBuilder.Entity("Tablero_MVC.Models.Tarea", b =>
                {
                    b.Property<int>("IDTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTarea"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoTarea")
                        .HasColumnType("int");

                    b.Property<int?>("TableroIDTablero")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTarea");

                    b.HasIndex("TableroIDTablero");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Tablero_MVC.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tablero_MVC.Models.Tablero", b =>
                {
                    b.HasOne("Tablero_MVC.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tablero_MVC.Models.Tarea", b =>
                {
                    b.HasOne("Tablero_MVC.Models.Tablero", null)
                        .WithMany("Tareas")
                        .HasForeignKey("TableroIDTablero");
                });

            modelBuilder.Entity("Tablero_MVC.Models.Tablero", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
